# Generated by Django 4.2.4 on 2023-08-30 19:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data_proj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataproj',
            name='devpost',
            field=models.CharField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataproj',
            name='github',
            field=models.CharField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
